"""Gerando tabelas novamente

Revision ID: 256e91d08fe1
Revises: 282ec6363977
Create Date: 2026-07-07 17:58:28.458761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '256e91d08fe1'
down_revision: Union[str, Sequence[str], None] = '282ec6363977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogadores_ativos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('codigo_time', sa.Integer(), nullable=True),
    sa.Column('abreviacao_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id')
    )
    op.create_table('jogadores_perfil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.String(), nullable=True),
    sa.Column('escola', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('altura', sa.String(), nullable=True),
    sa.Column('peso', sa.String(), nullable=True),
    sa.Column('posicao', sa.String(), nullable=True),
    sa.Column('numero_camisa', sa.String(), nullable=True),
    sa.Column('anos_experiencia', sa.String(), nullable=True),
    sa.Column('time_atual', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id')
    )
    op.create_table('stats_playoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.String(), nullable=True),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('player_age', sa.Float(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id', 'season_id', 'team_abbreviation', name='uix_stats_playoffs')
    )
    op.create_table('stats_temporada_regular',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.String(), nullable=True),
    sa.Column('team_abbreviation', sa.String(), nullable=True),
    sa.Column('player_age', sa.Float(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id', 'season_id', 'team_abbreviation', name='uix_stats_regular')
    )
    op.create_table('totais_carreira_playoffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id')
    )
    op.create_table('totais_carreira_regular',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('ast', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fg_pct', sa.Float(), nullable=True),
    sa.Column('fg3m', sa.Integer(), nullable=True),
    sa.Column('fg3a', sa.Integer(), nullable=True),
    sa.Column('fg3_pct', sa.Float(), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ft_pct', sa.Float(), nullable=True),
    sa.Column('oreb', sa.Integer(), nullable=True),
    sa.Column('dreb', sa.Integer(), nullable=True),
    sa.Column('reb', sa.Integer(), nullable=True),
    sa.Column('stl', sa.Integer(), nullable=True),
    sa.Column('blk', sa.Integer(), nullable=True),
    sa.Column('tov', sa.Integer(), nullable=True),
    sa.Column('fp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nba_player_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('equipe', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('totais_carreira_regular')
    op.drop_table('totais_carreira_playoffs')
    op.drop_table('stats_temporada_regular')
    op.drop_table('stats_playoffs')
    op.drop_table('jogadores_perfil')
    op.drop_table('jogadores_ativos')
    # ### end Alembic commands ###
