"""Alterar tipo coluna jogadores estatisticas

Revision ID: 282ec6363977
Revises: 5ec2cdf14feb
Create Date: 2026-07-07 00:24:06.718557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282ec6363977'
down_revision: Union[str, Sequence[str], None] = '5ec2cdf14feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'totais_carreira_playoffs', ['nba_player_id'])
    op.create_unique_constraint(None, 'totais_carreira_regular', ['nba_player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'totais_carreira_regular', type_='unique')
    op.drop_constraint(None, 'totais_carreira_playoffs', type_='unique')
    # ### end Alembic commands ###
