"""Alterar tipo coluna de jogadores_ativos

Revision ID: 5ec2cdf14feb
Revises: 0d0743e64396
Create Date: 2026-07-06 22:43:20.323852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec2cdf14feb'
down_revision: Union[str, Sequence[str], None] = '0d0743e64396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jogadores_ativos', 'abreviacao_time',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jogadores_ativos', 'abreviacao_time',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
